# Airflow database configuration
database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 
  name: airflow_test
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h
  # Mock mode, does not actually connect to the database
  mock: true

# Cleaning strategy configuration
cleaner:
  # Retention days, records older than these days will be cleaned
  retention_days:
    dag_run: 30        # DAG run records retained for 30 days
    task_instance: 30  # Task instances retained for 30 days
    xcom: 30           # XCom data retained for 30 days
    log: 30            # Logs retained for 30 days
    job: 30            # Job records retained for 30 days
    
  # Batch processing configuration
  batch_size: 1000     # Number of records processed per batch
  sleep_seconds: 0.5   # Interval time between batches (supports decimal values for milliseconds, e.g., 0.5 = 500ms)
  
  # Whether to perform actual delete operations, set to false to only display the number of records to be deleted
  dry_run: false
  
  # Whether to enable detailed logs
  verbose: false
  
  # Deletion method optimization
  # When true: Use primary key-based deletion (often faster for large tables)
  # When false: Use direct DELETE...WHERE...LIMIT method (simpler but can be slower)
  use_primary_key_delete: true

# Log configuration
log:
  level: info  # Log level: debug, info, warn, error
  file: ""     # Log file path, empty for standard output 