# Airflow数据库配置
database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 
  name: airflow_test
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h
  # 模拟模式，不实际连接数据库
  mock: true

# 清理策略配置
cleaner:
  # 保留天数，超过此天数的记录将被清除
  retention_days:
    dag_run: 14        # DAG运行记录保留14天
    task_instance: 14  # 任务实例保留14天
    xcom: 14           # XCom数据保留14天
    log: 7             # 日志保留7天
    job: 7             # Job记录保留7天
    
  # 批处理配置
  batch_size: 1000     # 每批处理的记录数
  sleep_seconds: 5     # 批次间隔时间(秒)，避免对数据库造成过大压力
  
  # 是否执行实际删除操作，设为false时只会显示将被删除的记录数量
  dry_run: false
  
  # 是否启用详细日志
  verbose: false

# 日志配置
log:
  level: info  # 日志级别: debug, info, warn, error
  file: ""     # 日志文件路径，为空则输出到标准输出 