# Airflow database configuration
database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 
  name: airflow_test
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h
  # Mock mode, does not actually connect to the database
  mock: true

# Cleaning strategy configuration
cleaner:
  # Retention days, records older than these days will be cleaned
  retention_days:
    dag_run: 14        # DAG run records retained for 14 days
    task_instance: 14  # Task instances retained for 14 days
    xcom: 14           # XCom data retained for 14 days
    log: 7             # Logs retained for 7 days
    job: 7             # Job records retained for 7 days
    
  # Batch processing configuration
  batch_size: 1000     # Number of records processed per batch
  sleep_seconds: 5     # Interval time between batches (seconds), to avoid excessive pressure on the database
  
  # Whether to perform actual delete operations, set to false to only display the number of records to be deleted
  dry_run: false
  
  # Whether to enable detailed logs
  verbose: false

# Log configuration
log:
  level: info  # Log level: debug, info, warn, error
  file: ""     # Log file path, empty for standard output 